version: "3"

services:
  bd:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
  backend:
    build: ./backend
    container_name: backend
    restart: always
    volumes:
      - ./backend:/app
    environment:
      - APP_NAME=webaplication
      - DB_USER=${DB_USER}
    ports:
      - "5000:5000"
