version: "3"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
  backend:
    build: ./backend
    container_name: backend
    restart: always
    volumes:
      - ./backend:/app
    environment:
      - APP_NAME=webaplication
      - DB_USER=${DB_USER}
    ports:
      - "${BACKEND_PORT}:5000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
